### ISSUE TITLE
ARC-Heavy: Make the dataset available

### ISSUE THREAD

**Issue by neoneye** [xu3kev/BARC#29]
I read your excellent paper. 

I couldn't find it inside this repo, maybe I overlooked it?

**Comment by xu3kev** [comment]
Hi,
Could you check the readme under [Synthetic Data Generation](https://github.com/xu3kev/BARC?tab=readme-ov-file#synthetic-data-generation) section?

**Comment by neoneye** [comment]
Aha, there are repos on huggingface. Huge thank you.

**Comment by neoneye** [comment]
Your ARC-Heavy is now available here:
https://github.com/neoneye/arc-dataset-collection/tree/main/dataset/ARC-Heavy

I have extracted the ARC puzzles from your huggingface repo, and saved them with ARC format. I have cherry picked 300 puzzles that doesn't resemble simple ARC-AGI puzzles.

Having inspected around 1200 ARC-Heavy puzzles, I'm very impressed how novel your puzzles are.

**Comment by xu3kev** [comment]
Really happy to hear your feedback about the puzzles being novel! Thanks for taking the time to review and share these. Looking forward to seeing how the community uses them!

**Comment by neoneye** [comment]
Your `ARC-Heavy` dataset can now be tried out in the browser.

https://neoneye.github.io/arc/?dataset=ARC-Heavy-a

https://neoneye.github.io/arc/?dataset=ARC-Heavy-b

**Comment by xu3kev** [comment]
It looks awesome and would be quite useful to examine them! Thanks for sharing these.
