### ISSUE TITLE
TTFT data generation

### ISSUE THREAD

**Issue by mertyg** [xu3kev/BARC#30]
Hi all, thank you for this great and super helpful release! I had a quick question. Which script is used to generate the test-time finetuning dataset? In particular, I'm looking for where the following is done:

> We choose each training example as a fake test example and do 10 times different randomly combined data augmentation for each fake task, which gives us 12k pseudo training dataset from the evaluation dataset. [...] The dataset size for test time fine-tuning is 22k in total.

Thanks!

**Comment by lillian039** [comment]
You can try this one: https://github.com/xu3kev/BARC/blob/master/data_processing/test-time-finetune/gen_test-time-dataset.sh

**Comment by lillian039** [comment]
And there is the script for test-time finetune: https://github.com/xu3kev/BARC/blob/master/finetune/alignment-handbook/recipes/barc/transduction_config_testtime-finetune_engineer_heavy_model.yaml
Hope it will help :)

**Comment by lillian039** [comment]
> Please try this one: https://github.com/xu3kev/BARC/blob/master/data_processing/test-time-finetune/gen_test-time-dataset.sh

Please try this one: https://github.com/xu3kev/BARC/blob/master/data_processing/test-time-finetune/gen_test-time-dataset.sh

And there is the script for test-time finetune: https://github.com/xu3kev/BARC/blob/master/finetune/alignment-handbook/recipes/barc/transduction_config_testtime-finetune_engineer_heavy_model.yaml
Hope it will help :)

**Comment by lillian039** [comment]
> Hi all, thank you for this great and super helpful release! I had a quick question. Which script is used to generate the test-time finetuning dataset? In particular, I'm looking for where the following is done:
> 
> > We choose each training example as a fake test example and do 10 times different randomly combined data augmentation for each fake task, which gives us 12k pseudo training dataset from the evaluation dataset. [...] The dataset size for test time fine-tuning is 22k in total.
> 
> Thanks!

Please try this one: https://github.com/xu3kev/BARC/blob/master/data_processing/test-time-finetune/gen_test-time-dataset.sh

And there is the script for test-time finetune: https://github.com/xu3kev/BARC/blob/master/finetune/alignment-handbook/recipes/barc/transduction_config_testtime-finetune_engineer_heavy_model.yaml
Hope it will help :)

**Comment by mertyg** [comment]
Thank you!
